---
- name: Oracle Database 19c Setup
  hosts: localhost
  become: yes

  tasks:
    - name: Create /etc/sysctl.d/98-oracle.conf with required parameters
      copy:
        dest: /etc/sysctl.d/98-oracle.conf
        content: |
          fs.file-max = 6815744
          kernel.sem = 250 32000 100 128
          kernel.shmmni = 4096
          kernel.shmall = 1073741824
          kernel.shmmax = 4398046511104
          kernel.panic_on_oops = 1
          net.core.rmem_default = 262144
          net.core.rmem_max = 4194304
          net.core.wmem_default = 262144
          net.core.wmem_max = 1048576
          net.ipv4.conf.all.rp_filter = 2
          net.ipv4.conf.default.rp_filter = 2
          fs.aio-max-nr = 1048576
          net.ipv4.ip_local_port_range = 9000 65500

    - name: Apply sysctl parameters
      command: /sbin/sysctl -p /etc/sysctl.d/98-oracle.conf

    - name: Create /etc/security/limits.d/oracle-database-preinstall-19c.conf
      copy:
        dest: /etc/security/limits.d/oracle-database-preinstall-19c.conf
        content: |
          oracle   soft   nofile    1024
          oracle   hard   nofile    65536
          oracle   soft   nproc    16384
          oracle   hard   nproc    16384
          oracle   soft   stack    10240
          oracle   hard   stack    32768
          oracle   hard   memlock    134217728
          oracle   soft   memlock    134217728

    - name: Install required packages
      dnf:
        name:
          - bc
          - binutils
          - compat-libstdc++-33
          - elfutils-libelf
          - elfutils-libelf-devel
          - fontconfig-devel
          - glibc
          - glibc-devel
          - ksh
          - libaio
          - libaio-devel
          - libXrender
          - libXrender-devel
          - libX11
          - libXau
          - libXi
          - libXtst
          - libgcc
          - librdmacm-devel
          - libstdc++
          - libstdc++-devel
          - libxcb
          - make
          - net-tools
          - nfs-utils
          - python3
          - python3-configshell
          - python3-rtslib
          - python3-six
          - targetcli
          - smartmontools
          - sysstat
          - gcc
          - unixODBC
          - libnsl
          - libnsl.i686
          - libnsl2
          - libnsl2.i686
        state: present
      ignore_errors: yes

    - name: Create groups
      group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
      loop:
        - { name: 'oinstall', gid: 54321 }
        - { name: 'dba', gid: 54322 }
        - { name: 'oper', gid: 54323 }
        # Uncomment and add more groups as required
        # - { name: 'backupdba', gid: 54324 }
        # - { name: 'dgdba', gid: 54325 }
        # - { name: 'kmdba', gid: 54326 }
        # - { name: 'asmdba', gid: 54327 }
        # - { name: 'asmoper', gid: 54328 }
        # - { name: 'asmadmin', gid: 54329 }
        # - { name: 'racdba', gid: 54330 }

    - name: Create oracle user
      user:
        name: oracle
        uid: 54321
        group: oinstall
        groups: dba,oper
        append: yes
        state: present

    - name: Set SELinux mode to permissive
      command: setenforce Permissive

    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Create Oracle directories
      file:
        path: "{{ item }}"
        state: directory
        owner: oracle
        group: oinstall
        mode: '0775'
      loop:
        - /u01/app/oracle/product/19.0.0/dbhome_1
        - /u02/oradata

