---
- name: Oracle Database 19c Setup
  hosts: localhost
  become: yes

  tasks:
    - name: Install Epel-Release Fedora
      yum:
       name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    - name: Create /etc/sysctl.d/98-oracle.conf with required parameters
      copy:
        dest: /etc/sysctl.d/98-oracle.conf
        content: |
          fs.file-max = 6815744
          kernel.sem = 250 32000 100 128
          kernel.shmmni = 4096
          kernel.shmall = 1073741824
          kernel.shmmax = 4398046511104
          kernel.panic_on_oops = 1
          net.core.rmem_default = 262144
          net.core.rmem_max = 4194304
          net.core.wmem_default = 262144
          net.core.wmem_max = 1048576
          net.ipv4.conf.all.rp_filter = 2
          net.ipv4.conf.default.rp_filter = 2
          fs.aio-max-nr = 1048576
          net.ipv4.ip_local_port_range = 9000 65500

    - name: Apply sysctl parameters
      command: /sbin/sysctl -p /etc/sysctl.d/98-oracle.conf

    - name: Create /etc/security/limits.d/oracle-database-preinstall-19c.conf
      copy:
        dest: /etc/security/limits.d/oracle-database-preinstall-19c.conf
        content: |
          oracle   soft   nofile    1024
          oracle   hard   nofile    65536
          oracle   soft   nproc    16384
          oracle   hard   nproc    16384
          oracle   soft   stack    10240
          oracle   hard   stack    32768
          oracle   hard   memlock    134217728
          oracle   soft   memlock    134217728

    - name: Install required packages
      dnf:
        name:
          - bc
          - binutils
          - compat-libstdc++-33
          - elfutils-libelf
          - elfutils-libelf-devel
          - fontconfig-devel
          - glibc
          - glibc-devel
          - ksh
          - libaio
          - libaio-devel
          - libXrender
          - libXrender-devel
          - libX11
          - libXau
          - libXi
          - libXtst
          - libgcc
          - librdmacm-devel
          - libstdc++
          - libstdc++-devel
          - libxcb
          - make
          - net-tools
          - nfs-utils
          - python3
          - python3-configshell
          - python3-rtslib
          - python3-six
          - targetcli
          - smartmontools
          - sysstat
          - gcc
          - unixODBC
          - libnsl*
          - libnsl.i686
          - libnsl2
          - libnsl2.i686
        state: present
      ignore_errors: yes

    - name: Create groups
      group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
      loop:
        - { name: 'oinstall', gid: 54321 }
        - { name: 'dba', gid: 54322 }
        - { name: 'oper', gid: 54323 }
        # Uncomment and add more groups as required
        # - { name: 'backupdba', gid: 54324 }
        # - { name: 'dgdba', gid: 54325 }
        # - { name: 'kmdba', gid: 54326 }
        # - { name: 'asmdba', gid: 54327 }
        # - { name: 'asmoper', gid: 54328 }
        # - { name: 'asmadmin', gid: 54329 }
        # - { name: 'racdba', gid: 54330 }

    - name: Create oracle user
      user:
        name: oracle
        uid: 54321
        group: oinstall
        groups: dba,oper
        append: yes
        state: present

    - name: Set SELinux mode to permissive
      command: setenforce Permissive

    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Create Oracle directories
      file:
        path: "{{ item }}"
        state: directory
        owner: oracle
        group: oinstall
        mode: '0775'
      loop:
        - /u01/app/oracle/product/19.0.0/dbhome_1
        - /data/oradata
      
    - name: Ensure permissions and ownership for /data directory
      file:
        path: /data
        owner: oracle
        group: oinstall
        mode: '0775'
        
    - name: Ensure permissions and ownership for /u01 directory
      file:
        path: /u01
        owner: oracle
        group: oinstall
        mode: '0775'
        
    - name: Create scripts directory
      file:
        path: /home/oracle/scripts
        state: directory
        owner: oracle
        group: oinstall
        mode: '0755'

    - name: Create setEnv.sh
      copy:
        dest: /home/oracle/scripts/setEnv.sh
        content: |
          # Oracle Settings
          export TMP=/tmp
          export TMPDIR=$TMP

          export ORACLE_HOSTNAME=ol8-19.localdomain
          export ORACLE_UNQNAME=cdb1
          export ORACLE_BASE=/u01/app/oracle
          export ORACLE_HOME=$ORACLE_BASE/product/19.0.0/dbhome_1
          export ORA_INVENTORY=/u01/app/oraInventory
          export ORACLE_SID=cdb1
          export PDB_NAME=pdb1
          export DATA_DIR=/u02/oradata

          export PATH=/usr/sbin:/usr/local/bin:$PATH
          export PATH=$ORACLE_HOME/bin:$PATH

          export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib
          export CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib

    - name: Set permissions for setEnv.sh
      file:
        path: /home/oracle/scripts/setEnv.sh
        owner: oracle
        group: oinstall
        mode: '0755'

    - name: Add reference to setEnv.sh in .bash_profile
      lineinfile:
        path: /home/oracle/.bash_profile
        line: '. /home/oracle/scripts/setEnv.sh'
        owner: oracle
        group: oinstall
        create: yes

    - name: Create start_all.sh
      copy:
        dest: /home/oracle/scripts/start_all.sh
        content: |
          #!/bin/bash
          . /home/oracle/scripts/setEnv.sh

          export ORAENV_ASK=NO
          . oraenv
          export ORAENV_ASK=YES

          dbstart $ORACLE_HOME

    - name: Set permissions for start_all.sh
      file:
        path: /home/oracle/scripts/start_all.sh
        owner: oracle
        group: oinstall
        mode: '0755'

    - name: Create stop_all.sh
      copy:
        dest: /home/oracle/scripts/stop_all.sh
        content: |
          #!/bin/bash
          . /home/oracle/scripts/setEnv.sh

          export ORAENV_ASK=NO
          . oraenv
          export ORAENV_ASK=YES

          dbshut $ORACLE_HOME

    - name: Set permissions for stop_all.sh
      file:
        path: /home/oracle/scripts/stop_all.sh
        owner: oracle
        group: oinstall
        mode: '0755'
